USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE OR REPLACE NETWORK RULE OPENTOPOMAP_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('opentopomap.org', 'tile.opentopomap.org', 'a.tile.opentopomap.org', 'b.tile.opentopomap.org', 'c.tile.opentopomap.org');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION CONTEXTILY_ACCESS
  ALLOWED_NETWORK_RULES = (
    SNOWFLAKE_LEARNING_DB.PUBLIC.OPENTOPOMAP_NETWORK_RULE
  )
  ENABLED = TRUE;